Repository jellyfin/jellyfin-android, pull requests merged in 2020-10, with the labels that each got.

#165 Rework app / webapp communication
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/Commands.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemoteVolumeProvider.kt
  app/src/main/java/org/jellyfin/mobile/webapp/WebViewController.kt
  app/src/main/java/org/jellyfin/mobile/webapp/WebappFunctionChannel.kt
Labels: enhancement

#166 Use fragments to separate UI components
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
  app/src/main/java/org/jellyfin/mobile/utils/PermissionRequestHelper.kt
  app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
  app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_connect.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_webview.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: code-cleanup/refactor, enhancement

#175 Initial database setup
  app/build.gradle.kts
  app/schemas/org.jellyfin.mobile.model.sql.JellyfinDatabase/1.json
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/mobile/model/DatabaseModule.kt
  app/src/main/java/org/jellyfin/mobile/model/sql/JellyfinDatabase.kt
  app/src/main/java/org/jellyfin/mobile/model/sql/dao/ServerDao.kt
  app/src/main/java/org/jellyfin/mobile/model/sql/dao/UserDao.kt
  app/src/main/java/org/jellyfin/mobile/model/sql/entity/ServerEntity.kt
  app/src/main/java/org/jellyfin/mobile/model/sql/entity/ServerUser.kt
  app/src/main/java/org/jellyfin/mobile/model/sql/entity/UserEntity.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#182 Audio device profile optimizations + exoplayer update
  app/src/main/assets/native/exoplayer.js
  app/src/main/java/org/jellyfin/mobile/player/ExoPlayerCodec.kt
  app/src/main/java/org/jellyfin/mobile/player/ExoPlayerFormats.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: code-cleanup/refactor, enhancement, exoplayer

#190 Add zoom feature to ExoPlayer
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
Labels: enhancement, exoplayer

#161 Add playback tracking support for mpv-android external player
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Labels: enhancement

#148 Add support for external player choice inside client settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/settings/ExternalPlayerPackage.java
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#194 Fix potential crashes in WebViewFragment
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
Labels: bug

#201 Use view binding in PlayerActivity
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/res/layout/activity_player.xml
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/layout/overlay_brightness_volume.xml
Labels: code-cleanup/refactor, enhancement, exoplayer

#143 Add android auto support
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
  app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/automotive_app_desc.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#200 adding forgotten featureGraphic
  fastlane/metadata/android/en-US/images/featureGraphic.png
Labels: enhancement

#203 Move video player into fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt
  app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
  app/src/main/java/org/jellyfin/mobile/utils/SmartOrientationListener.kt
  app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_connect.xml
  app/src/main/res/layout/fragment_player.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_webview.xml
  app/src/main/res/values-v28/styles.xml
  app/src/main/res/values-v29/styles.xml
  app/src/main/res/values/styles.xml
Labels: code-cleanup/refactor, enhancement, exoplayer

#215 Update Gradle to 6.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement

#217 Enable logging in release builds
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/mobile/utils/JellyTree.kt
Labels: enhancement

#216 Add RedScreenOfDeath for easy stacktraces
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#220 Dependency updates
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement
