Repository jellyfin/jellyfin-android, pull requests merged in 2020-08, with the labels that each got.

#23 Set ExoPlayer as disabled by default
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
Labels: exoplayer

#27 Fix possible exception when logging errors
  app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
Labels: bug

#26 Fix potential JSONException in NativeInterface, improve error handling
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
Labels: enhancement

#25 Add basic playback info dialog
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/res/drawable/ic_info_white_24dp.xml
  app/src/main/res/drawable/playback_info_background.xml
  app/src/main/res/layout/activity_player.xml
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, exoplayer

#30 Use constants for intent actions and extras
  app/src/main/java/org/jellyfin/mobile/RemotePlayerService.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Labels: enhancement

#29 Fix Activity leak
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/utils/LifecycleAwareHandler.kt
Labels: bug

#49 Add issue templates for GitHub
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#50 Split up web app and connection handling, use view binding for setup layout
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/ServerConnectionUtils.kt
  app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
  app/src/main/res/layout/activity_player.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_webapp.xml
  app/src/main/res/layout/connect_server.xml
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/values-b+es+419/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#51 Improve orientation handling
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/SmartOrientationListener.kt
Labels: enhancement

#53 Support Picture-in-Picture in ExoPlayer
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
Labels: enhancement, exoplayer

#54 Fullscreen and styles tweaks, system gestures support
  app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
  app/src/main/res/values-land-v28/styles.xml
  app/src/main/res/values-v29/styles.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#57 Refactoring and notification fix
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/Commands.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  app/src/main/java/org/jellyfin/mobile/webapp/WebViewController.kt
Labels: enhancement

#56 Kotlin 1.4
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
  gradle.properties
Labels: enhancement

#58 Add Koin (dependency injection)
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
  app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#61 MediaSource tweaks
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt
  app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#64 Use different application id, app name and icon for debug builds
  app/build.gradle.kts
  app/src/debug/res/drawable-v26/ic_launcher_foreground.xml
  app/src/debug/res/values/colors.xml
  app/src/debug/res/values/strings_donottranslate.xml
  app/src/main/res/drawable-v26/ic_launcher_foreground.xml
Labels: enhancement

#68 Add apiclient dependency, resolve device info via apiclient
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#74 Fix UI overlap by applying bottom insets
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
Labels: bug

#75 Show toast to restart app when changing ExoPlayer setting
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#76 Improve ExoPlayer enabling
  app/src/main/assets/native/exoplayer.js
  app/src/main/assets/native/nativeshell.js
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, exoplayer

#78 Use Coroutine Channels for Webapp communication
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerEvent.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/LifecycleAwareHandler.kt
Labels: enhancement

#80 Cleanup PlayerViewModel, externalize some callbacks
  app/src/main/java/org/jellyfin/mobile/player/PlayerLifecycleObserver.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerMediaSessionCallback.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
Labels: enhancement
