Repository jellyfin/jellyfin-android, pull requests merged in 2020-09, with the labels that each got.

#81 Add option for background audio playback in ExoPlayer, refactor notification handling in music player
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerLifecycleObserver.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerMediaSessionCallback.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/JSONExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  app/src/main/res/drawable/ic_rewind_black_32dp.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, exoplayer

#90 Update kotest, rename JUnit dependency
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: bug

#89 API client integration
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/api/TimberLogger.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/JSONExtensions.kt
  app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
  app/src/test/java/org/jellyfin/mobile/HelperTests.kt
Labels: enhancement

#92 Specify app backup content
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/backup_content.xml
Labels: enhancement

#97 Refactor image loading, add icon to background playback notification
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  app/src/main/res/values-v29/dimens.xml
  app/src/main/res/values/dimens.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#99 Simplify music notification icon handling
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
Labels: enhancement

#101 Resolve public system info via apiclient
  app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
Labels: enhancement

#103 Fix potential crash and set correct mimeType in loadAsset
  app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
Labels: bug, enhancement

#102 Remove unused functions from apphost.js, merge into nativeshell.js
  app/src/main/assets/index_patch.html
  app/src/main/assets/native/apphost.js
  app/src/main/assets/native/nativeshell.js
Labels: code-cleanup

#87 Improve script injection for native bridge
  app/src/main/assets/index_patch.html
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
  app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
Labels: enhancement

#104 ExoPlayer improvements: Submit playback status via apiclient, support remote seeking and volume changes
  app/src/main/assets/native/exoplayer.js
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerEvent.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/StdlibExtensions.kt
Labels: enhancement, exoplayer

#108 Add screen lock feature in ExoPlayer
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
  app/src/main/res/drawable/ic_screen_lock_white_24dp.xml
  app/src/main/res/drawable/ic_screen_unlock_white_24dp.xml
  app/src/main/res/drawable/playback_unlock_background.xml
  app/src/main/res/layout/activity_player.xml
  app/src/main/res/layout/exo_player_control_view.xml
Labels: enhancement, exoplayer

#107 Rework player implementation setting
  app/src/main/assets/native/externalplayer.js
  app/src/main/assets/native/nativeshell.js
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  app/src/main/java/org/jellyfin/mobile/settings/VideoPlayerType.java
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#110 Properly report playback stop events
  app/src/main/assets/native/exoplayer.js
  app/src/main/java/org/jellyfin/mobile/api/TimberLogger.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerLifecycleObserver.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
Labels: bug, code-cleanup, exoplayer

#111 ExoPlayer: Fix playlists (like intros) not working
  app/src/main/assets/native/exoplayer.js
  app/src/main/assets/native/externalplayer.js
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
Labels: bug, exoplayer

#113 Dependency updates and settings fixes
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle.properties
Labels: enhancement

#124 Dependency updates
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: code-cleanup, enhancement

#129 Refactor launcher icons
  app/src/debug/res/drawable-v26/ic_launcher_foreground.xml
  app/src/debug/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable-v26/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
Labels: code-cleanup, enhancement

#126 Implement auto discovery
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
  app/src/main/res/layout/connect_server.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#114 Use display language when available
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
Labels: enhancement

#133 Added Native Player Gesture for Volume & Brightness
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/res/drawable/ic_brightness_white_24dp.xml
  app/src/main/res/drawable/ic_volume_white_24dp.xml
  app/src/main/res/layout/activity_player.xml
  app/src/main/res/layout/overlay_brightness_volume.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, exoplayer

#154 Revert "Set appMode for webui"
  app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
Labels: bug
