Repository jellyfin/jellyfin-android, pull requests merged in 2021-08, with the labels that each got.

#477 Fix a rare crash when starting the app
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
Labels: bug

#482 Migrate to Gradle version catalogs
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/JellyfinSdk.kt
  buildSrc/src/main/kotlin/Plugins.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, code-cleanup/refactor

#484 Migrate bug report issue template to GitHub form
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#501 Fix direct play audio profiles
  app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt
Labels: bug

#507 WebView error handling tweaks
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
Labels: bug

#503 Properly open live streams before playback if necessary
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
Labels: bug, exoplayer

#508 Update AGP to 7.0.1
  build.gradle.kts
Labels: enhancement

#510 Update ExoPlayer to 2.15.0
  app/src/main/java/org/jellyfin/mobile/media/MediaNotificationManager.kt
  app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
  app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
  gradle/libs.versions.toml
Labels: exoplayer

#512 Force enable linear PCM codecs
  app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt
Labels: exoplayer
