Repository jellyfin/jellyfin-android, pull requests merged in 2021-06, with the labels that each got.

#412 Fix or suppress detekt warnings and code style issues
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
  app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt
  app/src/main/java/org/jellyfin/mobile/player/CodecHelpers.kt
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/JSONExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/PermissionRequestHelper.kt
  app/src/main/java/org/jellyfin/mobile/utils/StdlibExtensions.kt
  app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
  app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
  app/src/main/java/org/jellyfin/mobile/webapp/RemoteVolumeProvider.kt
  detekt.yml
Labels: code-cleanup/refactor, enhancement

#420 Update ExoPlayer to 2.14
  app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport, exoplayer

#426 Update weblate links
  README.md
Labels: backport

#427 Update to SDK beta 8
  app/src/main/java/org/jellyfin/mobile/controller/ApiController.kt
  app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
  app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport

#428 Add option to switch between versions of the SDK
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle.properties
Labels: backport

#431 Fix PiP crash on aspect ratios unsupported by Android
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Labels: bug, exoplayer

#442 Remember brightness changes on ExoPlayer
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerGestureHelper.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, exoplayer

#444 Follow state changes for brightness & gesture preference
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
Labels: enhancement, exoplayer

#439 Improve JS injection method
  app/src/main/assets/native/injectionScript.js
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
Labels: backport, enhancement

#436 Handle WebView error when loadUrl failed
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
Labels: enhancement

#445 Restructure Webapp UI
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
  app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
  app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_webview.xml
Labels: enhancement

#446 Sign APKs with apksigner instead of via Gradle
  .github/workflows/app-publish.yaml
Labels: backport, bug, ci

#448 fix odd release naming due to signing
  .github/workflows/app-publish.yaml
Labels: backport

#449 Append -release to release APKs
  .github/workflows/app-publish.yaml
Labels: ci
