Repository jellyfin/jellyfin-android, pull requests merged in 2021-05, with the labels that each got.

#352 Fix library browser recents
  app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt
Labels: bug

#358 Client settings layout and wording tweaks
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#359 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#361 Dependency updates + Detekt
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/model/sql/dao/UserDao.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  detekt.yml
Labels: enhancement

#362 Update Jellyfin SDK to beta 4
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#351 Migrate ExoPlayer to SDK and decouple from webapp
  app/src/main/assets/native/ExoPlayerPlugin.js
  app/src/main/assets/native/ExternalPlayerPlugin.js
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/api/ApiModule.kt
  app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt
  app/src/main/java/org/jellyfin/mobile/api/Extensions.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayerHost.kt
  app/src/main/java/org/jellyfin/mobile/bridge/PlayOptions.kt
  app/src/main/java/org/jellyfin/mobile/controller/ApiController.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/CodecHelpers.kt
  app/src/main/java/org/jellyfin/mobile/player/DeviceCodec.kt
  app/src/main/java/org/jellyfin/mobile/player/ExoPlayerCodec.kt
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerLifecycleObserver.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerMediaSessionCallback.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/ExoPlayerTrack.kt
  app/src/main/java/org/jellyfin/mobile/player/source/ExoPlayerTracksGroup.kt
  app/src/main/java/org/jellyfin/mobile/player/source/ExternalSubtitleStream.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
  app/src/main/java/org/jellyfin/mobile/webapp/WebappFunctionChannel.kt
  app/src/main/res/layout/exo_player_control_view.xml
Labels: code-cleanup/refactor, documentation, enhancement, exoplayer

#363 Make ExoPlayer the default video player implementation
  app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
Labels: enhancement, exoplayer

#364 Update Kotlin to 1.5.0
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle.properties
Labels: enhancement

#365 Fix app crashing when webview is missing
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
Labels: bug

#367 Treat recommended server without system info as unable to connect
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
Labels: backport

#377 Add desugaring to support java.time
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport

#374 Add snapshot repository for Jellyfin SDK
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle.properties
  settings.gradle.kts
Labels: enhancement

#381 Update SDK and rework server connection
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
  app/src/main/res/layout/fragment_connect.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: enhancement

#382 Fix various playback crashes
  app/src/main/assets/native/ExternalPlayerPlugin.js
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerException.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
  app/src/main/res/values/strings.xml
Labels: bug, exoplayer

#392 Add playback speed menu to ExoPlayer
  app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/res/drawable/ic_slow_motion_video_white_24dp.xml
  app/src/main/res/layout/exo_player_control_view.xml
Labels: enhancement, exoplayer

#394 Update SDK to beta 6
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport

#395 Fix CI failing and some small tweaks
  .github/workflows/app-build.yaml
  .github/workflows/app-publish.yaml
  .github/workflows/app-test.yaml
Labels: backport

#399 Workaround for coroutines crash
  app/src/main/java/org/jellyfin/mobile/player/source/Result.kt
Labels: backport, bug

#400 Update Kotlin to 1.5.10 and revert obsolete workaround
  app/src/main/java/org/jellyfin/mobile/player/source/Result.kt
  gradle.properties
Labels: backport, enhancement

#401 Update dependencies and fix deprecations
  app/src/main/assets/native/nativeshell.js
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
  app/src/main/java/org/jellyfin/mobile/webapp/WebappFunctionChannel.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport, enhancement

#403 Add gradle cache to app-build workflow
  .github/workflows/app-build.yaml
  .github/workflows/app-publish.yaml
Labels: backport

#404 Update Jellyfin SDK to 1.0.0 beta 7
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport, enhancement

#405 Library browser (Android Auto) tweaks
  app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt
Labels: backport, enhancement

#406 change directory structure of workflow artifacts
  .github/workflows/app-build.yaml
  .github/workflows/app-publish.yaml
Labels: backport, ci, github-actions

#410 Update SDK snapshot version to master-SNAPSHOT
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport

#411 Update and migrate Koin to 3.0.2
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
  app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
  app/src/main/java/org/jellyfin/mobile/media/MediaNotificationManager.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
  app/src/main/java/org/jellyfin/mobile/utils/DownloadMethod.java
  app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
  app/src/main/res/values-sq/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: backport, enhancement
