Repository jellyfin/jellyfin-android, pull requests merged in 2021-12, with the labels that each got.

#588 Update dependencies
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerLifecycleObserver.kt
  app/src/proprietary/java/org/jellyfin/mobile/cast/CastOptionsProvider.kt
  gradle/libs.versions.toml
Labels: dependencies

#575 Fix inconsistent behaviour of the previous button
  app/src/main/java/org/jellyfin/mobile/player/PlayerMediaSessionCallback.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
Labels: exoplayer, needs discussion

#589 Fix various cast code warnings
  app/src/proprietary/java/org/jellyfin/mobile/cast/ChromecastConnection.java
Labels: code-cleanup/refactor

#583 Apply explicit navigation bar color on API v28 and below
  app/src/main/res/values/styles.xml
Labels: bug
