Repository jellyfin/jellyfin-android, pull requests merged in 2021-10, with the labels that each got.

#447 Improve session integration
  app/src/main/java/org/jellyfin/mobile/api/ApiModule.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Labels: exoplayer

#441 Follow skip forward/back length on ExoPlayer
  app/src/main/java/org/jellyfin/mobile/api/ApiModule.kt
  app/src/main/java/org/jellyfin/mobile/model/DisplayPreferences.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerGestureHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Labels: enhancement, exoplayer

#540 Switch CI Java to temurin distribution
  .github/workflows/app-build.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-publish.yaml
  .github/workflows/app-test.yaml
Labels: ci, github-actions
