Repository jellyfin/jellyfin-android, pull requests merged in 2022-09, with the labels that each got.

#800 Rewrite connection screen in Jetpack Compose
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/MainViewModel.kt
  app/src/main/java/org/jellyfin/mobile/app/ApiClientController.kt
  app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
  app/src/main/java/org/jellyfin/mobile/setup/ConnectFragment.kt
  app/src/main/java/org/jellyfin/mobile/setup/ConnectionHelper.kt
  app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ConnectScreen.kt
  app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ServerSelection.kt
  app/src/main/java/org/jellyfin/mobile/ui/state/CheckUrlState.kt
  app/src/main/java/org/jellyfin/mobile/ui/state/ServerSelectionType.kt
  app/src/main/java/org/jellyfin/mobile/ui/utils/AppTheme.kt
  app/src/main/java/org/jellyfin/mobile/ui/utils/CenterRow.kt
  app/src/main/res/layout/fragment_compose.xml
  app/src/main/res/layout/fragment_connect.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_donottranslate.xml
  detekt.yml
  gradle/libs.versions.toml
Labels: enhancement

#816 Add pull request template
  .github/pull_request_template.md
Labels: documentation

#815 Update GitHub actions workflows
  .github/workflows/app-build.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-publish.yaml
  .github/workflows/app-test.yaml
  .github/workflows/gradlew-update.yaml
  .github/workflows/gradlew-validate.yaml
  .github/workflows/repo-merge-conflict.yaml
  .github/workflows/repo-stale.yaml
Labels: enhancement, ci
