Repository jellyfin/jellyfin-android, pull requests merged in 2022-04, with the labels that each got.

#635 Fix cast broken due to invalid manifest entry
  app/src/main/AndroidManifest.xml
Labels: bug, cast

#638 Add subtitle profiles to external player profile
  app/src/main/assets/native/ExternalPlayerPlugin.js
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
Labels: bug

#672 Update .editorconfig and fix formatting for renovate.json
  .editorconfig
  renovate.json
Labels: dependencies
