Repository jellyfin/jellyfin-android, pull requests merged in 2022-10, with the labels that each got.

#826 Add ability to direct play ass with exoplayer
  app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
  app/src/main/java/org/jellyfin/mobile/app/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, exoplayer

#842 Implement downloadFiles in NativeShell
  app/src/main/assets/native/nativeshell.js
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
Labels: enhancement

#869 Set namespace in build.gradle.kts instead of Manifest
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
Labels: code-cleanup/refactor

#866 Auto-apply milestones
  .github/workflows/repo-milestone.yaml
Labels: enhancement, ci, github-actions
