Repository jellyfin/jellyfin-android, pull requests merged in 2023-08, with the labels that each got.

#1134 Pre-fill last hostname and add history to suggestions in connect screen
  app/src/main/java/org/jellyfin/mobile/app/ApiClientController.kt
  app/src/main/java/org/jellyfin/mobile/data/dao/ServerDao.kt
  app/src/main/java/org/jellyfin/mobile/setup/ConnectFragment.kt
  app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ServerSelection.kt
  app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ServerSuggestion.kt
  app/src/main/java/org/jellyfin/mobile/ui/state/ServerSelectionMode.kt
Labels: enhancement

#1161 Fix deprecation and extract method
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
Labels: code-cleanup/refactor

#1166 Remove RedScreenOfDeath
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
  gradle/libs.versions.toml
Labels: code-cleanup/refactor, changelog-ignore

#1172 Introduce BackPressInterceptor
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/BackPressInterceptor.kt
  app/src/main/java/org/jellyfin/mobile/webapp/WebViewFragment.kt
Labels: enhancement

#1173 Allow to exit from fullscreen with the back button in ExoPlayer
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
Labels: enhancement, exoplayer

#1171 Fix app returning to WebViewFragment when activity restarts
  app/src/main/java/org/jellyfin/mobile/MainActivity.kt
Labels: bug
