Repository jellyfin/jellyfin-android, pull requests merged in 2023-04, with the labels that each got.

#1011 Add default changelog to fastlane
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: documentation, enhancement

#1012 Rework track handling and selection
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/ExternalSubtitleStream.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
  app/src/main/java/org/jellyfin/mobile/utils/TrackSelectionUtils.kt
Labels: bug

#1021 Fix subtitle selection for encoded subtitles
  app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
Labels: bug

#1033 Fix audio track selection if multiple renderers are used
  app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
Labels: bug

#1034 Update Jellyfin SDK (1.4.2) and Exoplayer (2.18.6)
  gradle/libs.versions.toml
Labels: dependencies, gradle
