Repository jellyfin/jellyfin-android, pull requests merged in 2023-05, with the labels that each got.

#1037 Improve notification handling
  app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationAction.kt
  app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
Labels: code-cleanup/refactor

#1038 Rewrite queue management and play options handling
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
Labels: exoplayer, code-cleanup/refactor

#1039 Fix audio track selection for >= 10 tracks
  app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
Labels: bug, exoplayer

#1041 Disable Google Safe Browsing Service in webviews
  app/src/main/AndroidManifest.xml
Labels: enhancement

#1044 Fix player menu track selection
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
Labels: bug, exoplayer

#1043 Add pgssub to ExoPlayer subtitle codecs
  app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
Labels: enhancement, exoplayer

#1059 Only play fullscreen video in ExoPlayer
  app/src/main/assets/native/ExoPlayerPlugin.js
Labels: bug, exoplayer

#1061 Don't overwrite milestone if applied already
  .github/workflows/repo-milestone.yaml
Labels: ci, github-actions

#1063 Fix insets handling on Android 10 and below
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFullscreenHelper.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
Labels: bug, exoplayer

#1065 Add workaround for non reproducible baseline profiles in AGP to libre builds
  app/baselineWorkaround.gradle
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: bug, gradle

#1069 Enable Renovate dependency dashboard
  renovate.json
Labels: dependencies

#1073 Fix bitrate not set for external player profile
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
Labels: bug

#1080 Fix milestone property always being undefined and thus non-null
  .github/workflows/repo-milestone.yaml
Labels: bug, ci, github-actions, changelog-ignore

#1076 Disable ExoPlayer and External player while in SyncPlay
  app/src/main/assets/native/ExoPlayerPlugin.js
  app/src/main/assets/native/ExternalPlayerPlugin.js
Labels: enhancement, exoplayer
