Repository jellyfin/jellyfin-android, pull requests merged in 2024-04, with the labels that each got.

#1337 Update dependency de.maxr1998:modernandroidpreferences to v2.4.0-beta2
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  gradle/libs.versions.toml
Labels: dependencies, gradle

#1364 Add new Jellyfin logo to connect screen
  app/src/debug/res/drawable/app_logo.xml
  app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ConnectScreen.kt
  app/src/main/java/org/jellyfin/mobile/ui/utils/CenterRow.kt
  app/src/main/res/drawable/app_logo.xml
  app/src/main/res/font/quicksand.ttf
Labels: enhancement

#1365 Remove baseline workaround
  app/baselineWorkaround.gradle
  app/build.gradle.kts
Labels: code-cleanup/refactor

#1366 Update fastlane graphics
  fastlane/metadata/android/en-US/images/featureGraphic.png
  fastlane/metadata/android/en-US/images/icon.png
Labels: enhancement
