Repository jellyfin/jellyfin-android, pull requests merged in 2025-05, with the labels that each got.

#1629 Fix webview closing on unimportant network errors
  app/src/main/java/org/jellyfin/mobile/webapp/JellyfinWebViewClient.kt
Labels: bug, backport

#1020 Add long press event for speeding up playing
  app/src/main/java/org/jellyfin/mobile/app/AppPreferences.kt
  app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerGestureHelper.kt
  app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
  app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#1627 Implement DownloadManagement app feature in nativeshell
  app/src/main/assets/native/nativeshell.js
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
Labels: enhancement

#1643 Fix syntax error in native shell JavaScript
  app/src/main/assets/native/nativeshell.js
Labels: bug

#1657 Fix various linter and compiler warnings
  app/build.gradle.kts
  app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
  app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
  app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
  app/src/main/java/org/jellyfin/mobile/data/entity/DownloadEntity.kt
  app/src/main/java/org/jellyfin/mobile/downloads/DownloadUtils.kt
  app/src/main/java/org/jellyfin/mobile/events/ActivityEventHandler.kt
  app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
  app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSourceSerializer.kt
  app/src/main/java/org/jellyfin/mobile/ui/content/ImageProvider.kt
  app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ServerSelection.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/VersionUtils.kt
Labels: code-cleanup/refactor

#1648 Fix integrated player control under camera cutout
  app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
Labels: bug, backport
